### ISSUE TITLE
prompts throw an error that have python template-like syntax with 0 parameter

### ISSUE THREAD

**Issue by Sneccello** [lve-org/lve#28]
If I
1.) Create a prompt like
"Please fill this template:
today's date: {todays_date}"

2.) set 
"prompt_parameters": [],
in the test.json

3.)
and run lve record ..

then it throws a KeyError for todays_date because its confused with prompt parameters even tho I did not give prompt parameters

**Comment by ayukh** [comment]
I had the same issue before, you can try to replace curly brackets `{todays_date}` with round ones `(todays_date)`. This fixed the problem for my case :)

**Comment by Viehzeug** [comment]
Will fix.

**Comment by Viehzeug** [comment]
I just checked and double escape, i.e. `{{test}}` already works.
It might be that it causes problems down the line (in the web renedering), but I'm happy to fix that if it comes to it.
