### ISSUE TITLE
Pip package is outdated

### ISSUE THREAD

**Issue by JasperDekoninck** [lve-org/lve#50]
Several issues now occur due to the pip installable package being quite old.

First, the openai version installed no longer works:

```openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`
```

Second, BiasChecker is not importable, disallowing me from recording instances for some of the reported vulnerabilities.

Adding one line of documentation to make it installable from source: (`cd lve-tools; pip install -e .`) would help with this issue. (Note that currently, the `transformers` and `torch` package are now missing from the requirements)

**Comment by lbeurerkellner** [comment]
Thanks for reporting.

We should probably also mention in the docs/README, that when you use the PyPi version of the tools, you will still need a local clone of the repository to create and run LVEs.

**Comment by lbeurerkellner** [comment]
We published a more up to date package and also updated the README/docs to mention that you will still need a clone of the repo, if you want to commit LVEs. Thanks again for reporting this.
