### ISSUE TITLE
[lve-tools] Custom checkers

### ISSUE THREAD

**Issue by mbalunovic** [lve-org/lve#8]
When adding a new LVE, we should allow creating a custom checker as part of the commit.
For example, one could create a folder `checker` inside of the LVE folder with a custom Python code and data needed for the checker. Right now custom checkers are limited to lambda functions which are often not enough.

**Comment by mbalunovic** [comment]
This should be addressed now with 8598b20c3ec002dfe6bf364ccb578f8ffa33f4f8.
Check out also 30bbb06531bf349627722639502729a47b49cb4a for the dummy LVE example that uses custom checker.

**Comment by lbeurerkellner** [comment]
Can we close this?
