### ISSUE TITLE
[lve-tools] Support for Chat format in test.prompt files

### ISSUE THREAD

**Issue by lbeurerkellner** [lve-org/lve#9]
The `lve` CLI should support parsing line-based Chat format directly from the `test.prompt` file. 

E.g. a `test.prompt` file of the following format, should be equivalent to specifying it in the `test.json` file:

```
{"role": "system", "content": "You are a calculator that only answers in single number results"}
{"role": "user", "content": "What is {a} + {b}?"}
```

**Comment by Viehzeug** [comment]
See [4e5797b](https://github.com/lve-org/lve/commit/4e5797bb0d2e29ea94b894fa1bfba3eeccdd91bb) for an implementation and the dummy lves there for the use.
Currently the "parser" guesses the used syntax from the content. However, we could also use file extensions to guide it.
